ALL_LINKS = 'SELECT * FROM links'
ALL_EMPLOYEES = 'SELECT * FROM employees'

INSERT_LINK = 'INSERT INTO links VALUES (?,?)'
INSERT_EMPLOYEE = 'INSERT INTO employees VALUES (?)'

DELETE_LINKS = 'DELETE FROM links WHERE boss=?'
DELETE_EMPLOYEE = 'DELETE FROM employees WHERE employee=?'
